# Generated by Django 3.2.8 on 2021-10-11 20:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('weight', models.PositiveIntegerField(null=True)),
                ('base_stats', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), null=True, size=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_to', to='api.pokemon')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
